<?php

namespace Database\Seeders;

use App\Models\Car;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CarsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cars = [
            [
                'id' => 1,
                'make' => 'Audi',
                'model' => 'A4',
                'year' => 2021,
                'license_plate' => 'AA-1001',
                'color' => 'white',
                'price_per_day' => 75.00,
                'mileage' => 28000,
                'transmission' => 'automatic',
                'seats' => 5,
                'fuel_type' => 'gasoline',
                'description' => 'Luxury sedan with premium features and smooth handling.',
                'available' => true,
            ],
            [
                'id' => 2,
                'make' => 'Audi',
                'model' => 'Q5',
                'year' => 2020,
                'license_plate' => 'AA-1002',
                'color' => 'white',
                'price_per_day' => 85.00,
                'mileage' => 35000,
                'transmission' => 'automatic',
                'seats' => 5,
                'fuel_type' => 'gasoline',
                'description' => 'Compact luxury SUV with all-wheel drive and spacious interior.',
                'available' => true,
            ],
            [
                'id' => 3,
                'make' => 'BMW',
                'model' => 'X5',
                'year' => 2022,
                'license_plate' => 'BB-2003',
                'color' => 'white',
                'price_per_day' => 120.00,
                'mileage' => 15000,
                'transmission' => 'automatic',
                'seats' => 7,
                'fuel_type' => 'gasoline',
                'description' => 'Premium SUV with advanced technology and exceptional performance.',
                'available' => true,
            ],
            [
                'id' => 4,
                'make' => 'Chevrolet',
                'model' => 'Camaro',
                'year' => 2021,
                'license_plate' => 'CC-3004',
                'color' => 'white',
                'price_per_day' => 95.00,
                'mileage' => 22000,
                'transmission' => 'manual',
                'seats' => 4,
                'fuel_type' => 'gasoline',
                'description' => 'Powerful sports car with aggressive styling and thrilling performance.',
                'available' => true,
            ],
            [
                'id' => 5,
                'make' => 'Chevrolet',
                'model' => 'Malibu',
                'year' => 2020,
                'license_plate' => 'CC-3005',
                'color' => 'white',
                'price_per_day' => 55.00,
                'mileage' => 42000,
                'transmission' => 'automatic',
                'seats' => 5,
                'fuel_type' => 'gasoline',
                'description' => 'Mid-size sedan offering comfort and fuel efficiency.',
                'available' => true,
            ],
            [
                'id' => 6,
                'make' => 'Chevrolet',
                'model' => 'Tahoe',
                'year' => 2021,
                'license_plate' => 'CC-3006',
                'color' => 'white',
                'price_per_day' => 110.00,
                'mileage' => 31000,
                'transmission' => 'automatic',
                'seats' => 8,
                'fuel_type' => 'gasoline',
                'description' => 'Full-size SUV with ample seating and towing capability.',
                'available' => true,
            ],
            [
                'id' => 7,
                'make' => 'Fiat',
                'model' => '500',
                'year' => 2019,
                'license_plate' => 'FF-4007',
                'color' => 'white',
                'price_per_day' => 40.00,
                'mileage' => 38000,
                'transmission' => 'manual',
                'seats' => 4,
                'fuel_type' => 'gasoline',
                'description' => 'Compact city car perfect for urban driving and parking.',
                'available' => true,
            ],
            [
                'id' => 8,
                'make' => 'Ford',
                'model' => 'Explorer',
                'year' => 2020,
                'license_plate' => 'FF-5008',
                'color' => 'white',
                'price_per_day' => 80.00,
                'mileage' => 36000,
                'transmission' => 'automatic',
                'seats' => 7,
                'fuel_type' => 'gasoline',
                'description' => 'Mid-size SUV with three rows and advanced safety features.',
                'available' => true,
            ],
            [
                'id' => 9,
                'make' => 'Ford',
                'model' => 'Focus',
                'year' => 2019,
                'license_plate' => 'FF-5009',
                'color' => 'white',
                'price_per_day' => 50.00,
                'mileage' => 45000,
                'transmission' => 'automatic',
                'seats' => 5,
                'fuel_type' => 'gasoline',
                'description' => 'Reliable compact car with good fuel economy.',
                'available' => true,
            ],
            [
                'id' => 10,
                'make' => 'Ford',
                'model' => 'Mustang',
                'year' => 2022,
                'license_plate' => 'FF-5010',
                'color' => 'white',
                'price_per_day' => 100.00,
                'mileage' => 12000,
                'transmission' => 'automatic',
                'seats' => 4,
                'fuel_type' => 'gasoline',
                'description' => 'Iconic American muscle car with powerful V8 engine.',
                'available' => true,
            ],
            [
                'id' => 11,
                'make' => 'GMC',
                'model' => 'Sierra_1500',
                'year' => 2021,
                'license_plate' => 'GG-6011',
                'color' => 'white',
                'price_per_day' => 90.00,
                'mileage' => 25000,
                'transmission' => 'automatic',
                'seats' => 6,
                'fuel_type' => 'gasoline',
                'description' => 'Full-size pickup truck with impressive towing capacity.',
                'available' => true,
            ],
            [
                'id' => 12,
                'make' => 'Honda',
                'model' => 'Civic',
                'year' => 2021,
                'license_plate' => 'HH-7012',
                'color' => 'white',
                'price_per_day' => 55.00,
                'mileage' => 24000,
                'transmission' => 'automatic',
                'seats' => 5,
                'fuel_type' => 'gasoline',
                'description' => 'Compact sedan known for reliability and fuel efficiency.',
                'available' => true,
            ],
            [
                'id' => 13,
                'make' => 'Hyundai',
                'model' => 'Sonata',
                'year' => 2020,
                'license_plate' => 'HH-8013',
                'color' => 'white',
                'price_per_day' => 60.00,
                'mileage' => 33000,
                'transmission' => 'automatic',
                'seats' => 5,
                'fuel_type' => 'gasoline',
                'description' => 'Mid-size sedan with modern design and advanced features.',
                'available' => true,
            ],
            [
                'id' => 14,
                'make' => 'Hyundai',
                'model' => 'Tucson',
                'year' => 2021,
                'license_plate' => 'HH-8014',
                'color' => 'white',
                'price_per_day' => 70.00,
                'mileage' => 28000,
                'transmission' => 'automatic',
                'seats' => 5,
                'fuel_type' => 'gasoline',
                'description' => 'Compact SUV with bold styling and comprehensive warranty.',
                'available' => true,
            ],
            [
                'id' => 15,
                'make' => 'Jaguar',
                'model' => 'F-Type',
                'year' => 2022,
                'license_plate' => 'JJ-9015',
                'color' => 'white',
                'price_per_day' => 180.00,
                'mileage' => 8000,
                'transmission' => 'automatic',
                'seats' => 2,
                'fuel_type' => 'gasoline',
                'description' => 'Luxury sports car with stunning design and exhilarating performance.',
                'available' => true,
            ],
            [
                'id' => 16,
                'make' => 'Jeep',
                'model' => 'Wrangler',
                'year' => 2021,
                'license_plate' => 'JJ-1016',
                'color' => 'white',
                'price_per_day' => 85.00,
                'mileage' => 20000,
                'transmission' => 'manual',
                'seats' => 4,
                'fuel_type' => 'gasoline',
                'description' => 'Rugged off-road SUV with removable doors and roof.',
                'available' => true,
            ],
            [
                'id' => 17,
                'make' => 'Kia',
                'model' => 'Optima',
                'year' => 2020,
                'license_plate' => 'KK-1117',
                'color' => 'white',
                'price_per_day' => 58.00,
                'mileage' => 37000,
                'transmission' => 'automatic',
                'seats' => 5,
                'fuel_type' => 'gasoline',
                'description' => 'Mid-size sedan with sporty design and value pricing.',
                'available' => true,
            ],
            [
                'id' => 18,
                'make' => 'Land Rover',
                'model' => 'Range Rover Sport',
                'year' => 2022,
                'license_plate' => 'LL-1218',
                'color' => 'white',
                'price_per_day' => 150.00,
                'mileage' => 10000,
                'transmission' => 'automatic',
                'seats' => 5,
                'fuel_type' => 'gasoline',
                'description' => 'Luxury SUV combining elegance with off-road capability.',
                'available' => true,
            ],
            [
                'id' => 19,
                'make' => 'Lexus',
                'model' => 'RX 350',
                'year' => 2021,
                'license_plate' => 'LL-1319',
                'color' => 'white',
                'price_per_day' => 95.00,
                'mileage' => 18000,
                'transmission' => 'automatic',
                'seats' => 5,
                'fuel_type' => 'gasoline',
                'description' => 'Luxury crossover SUV with refined comfort and reliability.',
                'available' => true,
            ],
            [
                'id' => 20,
                'make' => 'Mazda',
                'model' => 'CX-5',
                'year' => 2020,
                'license_plate' => 'MM-1420',
                'color' => 'white',
                'price_per_day' => 65.00,
                'mileage' => 32000,
                'transmission' => 'automatic',
                'seats' => 5,
                'fuel_type' => 'gasoline',
                'description' => 'Compact SUV with premium interior and engaging driving dynamics.',
                'available' => true,
            ],
            [
                'id' => 21,
                'make' => 'Mercedes-Benz',
                'model' => 'E-Class',
                'year' => 2022,
                'license_plate' => 'MM-1521',
                'color' => 'white',
                'price_per_day' => 130.00,
                'mileage' => 14000,
                'transmission' => 'automatic',
                'seats' => 5,
                'fuel_type' => 'gasoline',
                'description' => 'Executive luxury sedan with cutting-edge technology.',
                'available' => true,
            ],
            [
                'id' => 22,
                'make' => 'Mini',
                'model' => 'Cooper',
                'year' => 2020,
                'license_plate' => 'MM-1622',
                'color' => 'white',
                'price_per_day' => 50.00,
                'mileage' => 29000,
                'transmission' => 'manual',
                'seats' => 4,
                'fuel_type' => 'gasoline',
                'description' => 'Compact car with distinctive style and go-kart handling.',
                'available' => true,
            ],
            [
                'id' => 23,
                'make' => 'Mitsubishi',
                'model' => 'Outlander',
                'year' => 2019,
                'license_plate' => 'MM-1723',
                'color' => 'white',
                'price_per_day' => 60.00,
                'mileage' => 41000,
                'transmission' => 'automatic',
                'seats' => 7,
                'fuel_type' => 'gasoline',
                'description' => 'Mid-size SUV with three rows and 10-year warranty.',
                'available' => true,
            ],
            [
                'id' => 24,
                'make' => 'Nissan',
                'model' => 'Altima',
                'year' => 2020,
                'license_plate' => 'NN-1824',
                'color' => 'white',
                'price_per_day' => 57.00,
                'mileage' => 34000,
                'transmission' => 'automatic',
                'seats' => 5,
                'fuel_type' => 'gasoline',
                'description' => 'Mid-size sedan with intelligent all-wheel drive available.',
                'available' => true,
            ],
            [
                'id' => 25,
                'make' => 'Porsche',
                'model' => '911 Carrera',
                'year' => 2022,
                'license_plate' => 'PP-1925',
                'color' => 'white',
                'price_per_day' => 250.00,
                'mileage' => 5000,
                'transmission' => 'automatic',
                'seats' => 4,
                'fuel_type' => 'gasoline',
                'description' => 'Iconic sports car delivering legendary performance and handling.',
                'available' => true,
            ],
            [
                'id' => 26,
                'make' => 'Subaru',
                'model' => 'Impreza',
                'year' => 2020,
                'license_plate' => 'SS-2026',
                'color' => 'white',
                'price_per_day' => 52.00,
                'mileage' => 39000,
                'transmission' => 'manual',
                'seats' => 5,
                'fuel_type' => 'gasoline',
                'description' => 'Compact car with standard all-wheel drive and excellent safety.',
                'available' => true,
            ],
            [
                'id' => 27,
                'make' => 'Tesla',
                'model' => 'Model 3',
                'year' => 2021,
                'license_plate' => 'TT-2127',
                'color' => 'white',
                'price_per_day' => 85.00,
                'mileage' => 16000,
                'transmission' => 'automatic',
                'seats' => 5,
                'fuel_type' => 'electric',
                'description' => 'All-electric sedan with autopilot and over-the-air updates.',
                'available' => true,
            ],
            [
                'id' => 28,
                'make' => 'Toyota',
                'model' => 'Camry',
                'year' => 2021,
                'license_plate' => 'TT-2228',
                'color' => 'white',
                'price_per_day' => 62.00,
                'mileage' => 26000,
                'transmission' => 'automatic',
                'seats' => 5,
                'fuel_type' => 'gasoline',
                'description' => 'Mid-size sedan known for reliability and resale value.',
                'available' => true,
            ],
            [
                'id' => 29,
                'make' => 'Volkswagen',
                'model' => 'Golf',
                'year' => 2020,
                'license_plate' => 'VV-2329',
                'color' => 'white',
                'price_per_day' => 55.00,
                'mileage' => 31000,
                'transmission' => 'manual',
                'seats' => 5,
                'fuel_type' => 'gasoline',
                'description' => 'Compact hatchback with European engineering and build quality.',
                'available' => true,
            ],
            [
                'id' => 30,
                'make' => 'Volvo',
                'model' => 'XC60',
                'year' => 2021,
                'license_plate' => 'VV-2430',
                'color' => 'white',
                'price_per_day' => 88.00,
                'mileage' => 21000,
                'transmission' => 'automatic',
                'seats' => 5,
                'fuel_type' => 'gasoline',
                'description' => 'Luxury compact SUV with advanced safety technology.',
                'available' => true,
            ],
        ];


        foreach ($cars as $data) {
            Car::query()->updateOrCreate(
                ['license_plate' => $data['license_plate']],
                $data
            );

            $make = str_replace(' ', '_', $data['make']);
            $modelName = str_replace(' ', '_', $data['model']);

            DB::insert('insert into files (original_name, filename, path, mime_type, size, collection, fileable_id, fileable_type) values (?, ?, ?, ?, ?, ?, ?, ?)', [
                $make . '_' . $modelName,
                $make . '_' . $modelName . '.webp',
                'files/car/' . $data['id'] . '/image/' . $make . '_' . $modelName . '.webp',
                'image/webp',
                100,
                'image',
                $data['id'],
                Car::class
            ]);
        }
    }
}
